### ISSUE TITLE
la calificación o marca de completado no pasa a coursera

### ISSUE THREAD

**Issue by darianos** [MOOC-tutorials/git_web_practice_branch#26]
la herramienta ya funciona pero la herramienta no pasa la marca de completado a coursera sino que abre una página con el error 403 y el siguiente mensaje 

Forbidden
You don't have permission to access this resource.

Apache/2.4.41 (Ubuntu) Server at misovirtual.virtual.uniandes.edu.co Port 443

**Comment by eclaro1974** [comment]
buenas tardes, estoy haciendo e taller, es posible que se me de permiso?

**Comment by CARLMHF** [comment]
como te doy permiso?

**Comment by eclaro1974** [comment]
Buenas tardes.
Muchas gracias, retomé la practica desde cero borrando los repositorios y logré completarlos.
Cordial saludo.

**Comment by slalozanos** [comment]
tiene fallas
